/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package procedimiento;

import javax.swing.JOptionPane;

/**
 *
 * @author Marcos Sarmientos
 */
public class Viajes extends javax.swing.JFrame {

    /**
     * Creates new form Viajes
     */
    public Viajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtIntegrantes = new javax.swing.JTextField();
        txtDias = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setText("Numero de integrantes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Numero de dias en el tour");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setText("Cobro total con 12% de iva ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        txtIntegrantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIntegrantesKeyTyped(evt);
            }
        });
        getContentPane().add(txtIntegrantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 80, -1));

        txtDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiasActionPerformed(evt);
            }
        });
        txtDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiasKeyTyped(evt);
            }
        });
        getContentPane().add(txtDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 80, 20));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
     int integrantes, dias;
     double total, iva, total1;
     String todo;

     if(txtIntegrantes.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite el número de integrantes","error", JOptionPane.ERROR_MESSAGE);  
        txtIntegrantes.requestFocusInWindow();
        txtIntegrantes.selectAll();
     }  
     else if(txtDias.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(this, "Digite la cantidad de días","error", JOptionPane.ERROR_MESSAGE);  
        txtDias.requestFocusInWindow(); 
         txtDias.selectAll();    
     }
     else{
     integrantes=Integer.parseInt(txtIntegrantes.getText());
     dias=Integer.parseInt(txtDias.getText());
    
     if(integrantes==0) {
       JOptionPane.showMessageDialog(this, "No existen personas ","Note", JOptionPane.INFORMATION_MESSAGE);  
        txtIntegrantes.requestFocusInWindow(); 
        txtIntegrantes.selectAll();  
     }  
     else if(dias==0){
     JOptionPane.showMessageDialog(this, "Digite los dias de estadía en el Tour","Error", JOptionPane.ERROR_MESSAGE);  
        txtDias.requestFocusInWindow(); 
        txtDias.selectAll();              
       }    
    total1=((dias*25000)*integrantes);
    iva=(total1*0.12);
    total=(total1+iva);

    todo=String.valueOf(total);
    txtTotal.setText (todo);
     }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void txtIntegrantesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIntegrantesKeyTyped
        char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume(); 
          } 
    }//GEN-LAST:event_txtIntegrantesKeyTyped

    private void txtDiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiasKeyTyped
        char c=evt.getKeyChar(); 
       
          if(!Character.isDigit(c)) { 
              getToolkit().beep();    
              evt.consume(); 
          } 
    }//GEN-LAST:event_txtDiasKeyTyped

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
     txtIntegrantes.setText("");
     txtDias.setText("");
     txtTotal.setText("");
     txtIntegrantes.requestFocusInWindow();  
    }//GEN-LAST:event_cmdBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtIntegrantes;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
